pool: $(AZURE_AGENT)

trigger:
  batch: true
  branches:
    include:
      - refs/tags/*
      - master

    exclude:
      - feature/*
      - bugfix/*
      - release/*

jobs:
  - job: testing
    displayName: Install dependencies and Run Tests
    steps:
      - task: Docker@1
        inputs:
          dockerFile: Dockerfile
          imageName: {{cookiecutter.package_name}}
          arguments: --target tester

  {%- if cookiecutter.publish_in == "Private PyPI"%}
  - job: publish_wheel
    
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

    displayName: Publish Wheels
    variables:
      ARTIFACT_FEED: $(ARTIFACT_FEED)
    dependsOn:
      - testing
          
    steps:
      - task: TwineAuthenticate@1
        displayName: Twine Authenticate
        inputs:
          artifactFeed: $(ARTIFACT_FEED)

      - task: Docker@1
        inputs:
          dockerFile: Dockerfile
          imageName: {{cookiecutter.package_name}}
          arguments: --build-arg ARTIFACT_FEED=${ARTIFACT_FEED} --build-arg PYPIRC_PATH=${PYPIRC_PATH} --target publisher 
  {%- elif cookiecutter.publish_in == "ACR"%}
  - job: publish
    variables:
      tag: $(Build.BuildId)
      acr: $(acr)
      acrRepository: $(acrRepository)

    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    dependsOn:
      - build
    displayName:  Publish to ACR
    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: $(acr)

      - task: Docker@2
        displayName: Push
        inputs:
          arguments: --target base
          command: push
          containerRegistry: $(acr)
          repository: $(acrRepository)
          tags: |
            latest
            $(tag)
  {%- endif %}